# -*- coding: utf-8 -*-
"""2.1-Variáveis-Exercícios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bI0s23G3Sonx5FlO-UDPwxeVgdNe_pKR

# Módulo 2
## 2.1 Variáveis

### Q1.
Selecione todos os itens a seguir que contém nomes válidos de variáveis. Lembre-se que alguns nomes com estrutura válida são palavras reservadas da linguagem e portanto não podem nomear variáveis.

    a) nome_completo
    b) quantidade@produtos
    c) idade
    d) soma idades
    e) MediaNotas
    f) _tipo
    g) 2total
    h) lambda
"""

# Preencha o print com as alternativas corretas
# separadas por espaços em branco.
# Ex: print("a b c")
print(" a c e f g ")

"""---
### Q2.
Dados os scripts a seguir, faça:
- Para os scripts corretos escreva o resultado impresso ao final da execução
- Para os incorretos descreva todos os erros identificados apontando a linha onde cada erro acontece.

```python
# Script 1
x = 10
y = x + 2
print(y - 5)
```
"""

# preencha o print com sua resposta
print(" 7 ")

"""```python
# Script 2
soma = n1 + n2
print(soma)
```
"""

# preencha o print com sua resposta
print(" O erro está na primeira linha abaixo de #Script 2, pois, apesar da sintaxe estar correta, as variáveis n1 e n2 não existem dentro do script apresentado. ")

"""```python
# Script 3
a = 10
a = a + 1
print(a)
```
"""

# preencha o print com sua resposta
print(" 11 ")

"""```python
# Script 4
saldo da conta = 1500
0.1 = juros
print(saldo da conta * juros)
```
"""

# preencha o print com sua resposta
print(" Na primeira linha abaixo de #Script 4, o nome da variável não é válido, pois há a presença de espaços, sendo que são aceitos apenas letras, números e -underlines- para nomear variáveis. Na segunda linha o nome da variável está à direita do sinal de igualdade e o seu valor está à esquerda, sendo que o nome deve ficar à esquerda e o valor à direita, tratando-se, portanto, de um erro. ")

"""---
### Q3.
Declare três variáveis, `num1`, `num2` e `num3`, com valores inteiros numéricos de sua escolha. Calcule e imprima a média desses três números. Utilize a fórmula: `(num1 + num2 + num3) / 3`.
"""

## Escreva e execute seu código aqui
num1 = 5
num2 = 10
num3 = 3
media = (num1 + num2 + num3) / 3
print(media)

"""---
### Q4.
Escreva um script python que:
- Armazene em uma variável uma velocidade de 90 km/h
- Calcule e armazene o equivalente em m/s
    - Divida o valor original por 3.6 para obter o resultado em m/s. Em python a sintaxe da divisão e atribuição é c = a / b
- Imprima na tela a velocidade o resultado m/s

"""

## Escreva e execute seu código aqui
kmh= 90
ms= kmh/3.6
print("90km/h em metros por segundo corresponde a:")
print(ms)

"""---
### Q5.
Escreva um script python que:
- Armazene o seu nome em uma variável
    - Dica: para armazenar textos em variáveis basta colocar a palavra desejada entre aspas, ex: "Camila", à direita do operador de atribuição.
- Imprima o texto "Meu nome é:"
- Imprima a variável com seu nome

"""

## Escreva e execute seu código aqui
nome= "Marco Antônio"
print("Meu nome é:")
print(nome)